title: BachemaVBA
description: Häufig benutzte VBA Module in Auswertungen
theme: just-the-docs

baseurl: /
url: https://nielll.github.io/BachemaVBA

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/nielll/BachemaVBA
